export const CONNECT_SOCKET_REQUESTED = 'CONNECT_SOCKET_REQUESTED'
export const CONNECT_SOCKET_SUCCEEDED = 'CONNECT_SOCKET_SUCCEEDED'
export const CONNECT_SOCKET_FAILED    = 'CONNECT_SOCKET_FAILED'

export const QUERY_USER_REQUESTED     = 'QUERY_USER_REQUESTED'
export const QUERY_USER_RECEIVED      = 'QUERY_USER_RECEIVED'
export const QUERY_INSTANCE_REQUESTED = 'QUERY_INSTANCE_REQUESTED'
export const QUERY_INSTANCE_RECEIVED  = 'QUERY_INSTANCE_RECEIVED'
export const QUERY_UNKNOWN_RECEIVED   = 'QUERY_UNKNOWN_RECEIVED'

export const USER_ENTER_INSTANCE_REQUESTED = 'USER_ENTER_INSTANCE_REQUESTED'
export const USER_LEAVE_INSTANCE_REQUESTED = 'USER_LEAVE_INSTANCE_REQUESTED'

export const WINDOW_RESIZE_EVENT_RECEIVED = 'WINDOW_RESIZE_EVENT_RECEIVED'